### ISSUE TITLE
Background icons behind top-row badges move down and left as they scale

### ISSUE THREAD

**Issue by luc-ass** [pi-hole/web#1747]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform

- OS and version:  Docker

- Platform:  Synology NAS (DS916+)

### Expected behavior

The icons behind the top badges on the start page should only get a little bigger.

### Actual behavior / bug

Icons behind the top badges get somewhat bigger `font-size: 90px;` → `font-size: 95px;` but also moves down and to the left because `top: -10px;` and `right: 10px` are not changed on hover. 

### Steps to reproduce

1. Hover mouse over badges in the top row

### Additional context

This can be fixed by changing the css from:
```css
.small-box:hover .icon {
    font-size: 95px;
}
```
to:
```css
.small-box:hover .icon {
    font-size: 95px;
    top: -14px;
    right: 7px;
}
```

Hey there!

I have no idea if this should be changed within Admin-LTE or if this needs to be changed within the actual bootstrap template. Please let me know how you like it and wether to implement it.

**Comment by DL6ER** [comment]
Do you have screenshots showing the difference before/with your change?

You should change the styling for these elements here: https://github.com/pi-hole/AdminLTE/blob/master/style/pi-hole.css

**Comment by luc-ass** [comment]
Sure! It looks like this:

before:
![n5SY5AtNRL](https://user-images.githubusercontent.com/3263257/108630077-5b765c80-7463-11eb-92fc-fd99e8f8ac5c.gif)

after: 
![dO4r9vzsP8](https://user-images.githubusercontent.com/3263257/108630072-57e2d580-7463-11eb-8c6e-d99715a24c22.gif)

Still not sure wether it should be fixed in the parent theme. I'll make a pull request as a fix for the time being.

**Comment by luc-ass** [comment]
WIP https://github.com/pi-hole/AdminLTE/pull/1748

**Comment by PromoFaux** [comment]
Just as a note, this may already have been fixed upstream. We're using a fairly old version of AdminLTE at the moment (only because it's a bit of a slog to update to v3) - though someone did start looking at it once: https://github.com/pi-hole/AdminLTE/tree/adminlte-3

**Comment by rdwebdesign** [comment]
Suggestion:

On hover, do not use `font-size` to change de icon size, use `transform: scale()`:

Add to _pi-hole.css_:
```css
.small-box:hover .icon {
    font-size: 90px; /* keep the same font-size */
    transform: scale(106%);
}
```

`transform` will scale the icon, keeping it centered.
