### ISSUE TITLE
After datatables update, tables are no longer striped

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/web#2867]
Tables lost the zebra-stripes effect.

The original bootstrap CSS:
```css
.table-striped > tbody > tr:nth-of-type(2n+1) {
  background-color: #f9f9f9;
}
```

Is overwritten by datatables CSS:
```css
table.dataTable.table-striped > tbody > tr:nth-of-type(2n+1) {
  background-color: transparent;
}
```
