### ISSUE TITLE
some settings tabs often will not load

### ISSUE THREAD

**Issue by tgaff** [pi-hole/web#2959]
### Versions

- Pi-hole:  Pi-hole version is v5.17.3 (Latest: v5.17.3)
- AdminLTE:  web version is v5.21 (Latest: v5.21)
- FTL:    FTL version is v5.24 (Latest: v5.24)

### Platform

- OS and version:  Debian GNU/Linux 11 (bullseye)

- Platform:  pihole docker

### Expected behavior

All tabs on the Settings page should load.

### Actual behavior / bug

They do not load.  Specifically the following tabs do not load:
 - Web interface
 - API
 - Privacy
 - Teleporter

**But sometimes they do load.**  I initially was convinced this was related to whether 3rd party cookies were allowed by the browser settings but now I'm convinced it has to do with the JS transition for the tab implementation.  I haven't checked what tech is behind the pihole web app but inspecting the HTML when the problem is happening is showing that the `active in` and `fade` classes on the relevant panels are not swapping as I believe they should.

### Steps to reproduce

1. Go to settings
2. click DHCP (may not be necessary but seems it happens most often from this starting point)
3. observe DHCP tab content displayed and DHCP tab is highlighted
4. click Web Interface
5. observed Web Interface content *does not* display but Web interface tab is highlighted.
    a. repeat for API, Privacy and Teleporter tabs
6. If you **did not see the bug** in the previous step then:
   a. click the System tab
   b. hard refresh (in Chrome on MacOS Cmd+Shift+R)
   c. observe system tab
   d. return to step 2 and repeat
   
 
## Debug Token

- URL:  https://tricorder.pi-hole.net/d4TxAHVc/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

I spent two days thinking this was a permissions issue and then a cookies issue.  Now I think it's JS.  If I still sound sane and someone want to point me towards where the relevant source code is I'd be happy to take a first peek at it.  :she

**Comment by DL6ER** [comment]
Do you see any errors in the "Console" (check the developer tools you can summon using <kbd>F12</kbd>)?

**Comment by tgaff** [comment]
> Do you see any errors in the "Console" (check the developer tools you can summon using F12)?

No.  I spent a fair bit of time looking at the networking section and then inspecting the page itself.  Never once saw an error.
![Screen Shot 2024-02-14 at 11 29 10 AM](https://github.com/pi-hole/web/assets/1916144/68d07d91-9bb9-4a6a-b2c5-78cd5b98e27b)

> One more question:
> 
> * Do you see the same behavior after disabling all browser extensions?

I see it in incognito mode in both Brave and Firefox.

**Comment by tgaff** [comment]
Decided to try a different OS too.  On Firefox Focus on Android 14 I get very similar behavior.  The only difference I noted was that the "Web Interface" tab worked but API, Privacy and Teleporter still did not display.  At least in 2 out of 3 tries.

Also I've reproduced this with both the docker images:
- pihole/pihole:2023.02.1
- rlabinc/pihole-unbound:latest

**Comment by tgaff** [comment]
In addition I just realized that on some of those tabs text is cut-off.  (seen in FF and Brave using both pihole/pihole:2024.01.0
rlabinc/pihole-unbound:latest)

![Screen Shot 2024-02-14 at 12 05 09 PM](https://github.com/pi-hole/web/assets/1916144/7dfcfc32-7549-4ade-881f-554f2e325a35)

This may be a separate issue.

**Comment by rdwebdesign** [comment]
Please, post your current compose file or `docker run` command used to start the container.

**Comment by rdwebdesign** [comment]
> I just realized that on some of those tabs text is cut-off. 
> (...)
> This may be a separate issue.

No... Actually this could explain what you see in the browser.

If the page is incomplete, one or more tabs will be incomplete.
The end of one tab could be "mixed" with other tab and javascript code will show a tab different than expected.

The real question is: **What is causing this? Why the pages are broken?** 

You are trying with many different images, but no other users saw this behavior, so it is very unlikely the issue in on the images.

It must be something on your system.

Are you using a volume to store the web interface (`/var/www/html/admin`)?

**Comment by tgaff** [comment]
OK, I think you could be on to something.

In order to get past an error showing in a red banner at the top I set a couple of variables. Error: `There was a problem applying your settings.` `PHP error (2): parse_ini_file(/etc/pihole/setupVars.conf): failed to open stream: Permission denied in /var/www/html/admin/settings.php:17`

Specifically I set WEB_UID or PIHOLE_GID.  They're marked Experimental in the docker README.  Setting these allowed me to get past the error and save changes.

```yaml
# https://hub.docker.com/r/pihole/pihole
version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pinhole
    hostname: pi.hole
    image: pihole/pihole:2024.01.0
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: $TZ
      WEBPASSWORD: $PW
      WEB_UID: 1003
      PIHOLE_GID: 100
    # Volumes store your data between container upgrades
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/pihole/etc-pihole:/etc/pihole
      - CHANGE_TO_COMPOSE_DATA_PATH/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    
    networks:
      pihole_ipvlan:
        ipv4_address: 192.168.0.203

networks:
  pihole_ipvlan:
    external: true
```
_Note: You can ignore `CHANGE_TO_COMPOSE_DATA_PATH` it's automatically substituted for a real path owned by `appuser:users` or 1003 100_

If you can point me toward any documentation on the UID/GID settings it might help in further debugging.  What I had known based on the README is:
- PIHOLE_UID and WEB_UID shouldn't be the same
- PIHOLE_GID and WEB_GID shouldn't be the same
- PIHOLE_UID and WEB_UID shouldn't conflict with values in the container.

Also the container UID/GIDs
- values in container for Groups are 0-60, 100, 65534, 101 and 1000(pihole)
- values in container for user ids are 0-13, 33 (www-data), 34, 38, 39, 41, 65534, 100 and 999(pihole)

There was technically a conflict with PIHOLE_GID being set to 100 (hosts's users account overlapping docker's users account) but I'm able to reproduce the issue even after removing PIHOLE_GID (and of course restarting) so I don't think that's it.
